version: 2
updates:
  - package-ecosystem: "gomod"
    rebase-strategy: "auto"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
